### PR TITLE
Simplify CI

### PR DESCRIPTION
**Pull request by Arthri**
- Simplified CI by deduplicating jobs using Actions' matrixes
- Unified zipping program to 7z(it is installed in all three runners Actions supports)
- Fixed Windows' Launcher zip starting with `publish`
- Fixed Linux's launcher zip starting with `bin/Release/net6.0/ubuntu.16.04-x64/publish`

### CODE REVIEW

**Comment by SignatureBeef** [comment]
This looks great to me. I've also added actions/setup-dotnet@v3 to settings now, so jobs should be able to run with this now too...hopefully.

**Comment by Arthri** [comment]
Reopening to retrigger CI

**Comment by Arthri** [comment]
Sorry, I forgot to fix the working directory thing with ModFramework

**Comment by Arthri** [comment]
As far as I can tell, the previous run was not able to load the C# modules, signified by the lack of `[CSharp]` logs that are normally there. Causing MonoMod to crash

**Comment by SignatureBeef** [comment]
Latest build appears to be ok now, i think, Really dig the changes, haven't really had time to improve stuff like this myself so thank you 🙏

**Pull request merged**
